### ISSUE TITLE
Upgrade to the latest Joomla! version

### ISSUE THREAD

**Issue by offiria** [offiria/offiria#1]
Which is 2.5.14

**Comment by amejat** [comment]
Would it resolve all PHP 5.4 issues or is there also issues in Offiria specific code ? 
Moreover, do you consider Joomla 2.5 only ? Or also Joomla 3 version ?

**Comment by JMSolo** [comment]
I have successfully updated it to LTS 2.5.14 and there have been no issues.  None other than the few that are found within the other issues listed.

**Comment by offiria** [comment]
Pushing 2.5.14 codes

**Comment by offiria** [comment]
Updated..
