### ISSUE TITLE
https in (invite) messages

### ISSUE THREAD

**Issue by Netbulae** [offiria/offiria#120]
We run https only webservers but the invit e-mail and probably other e-mail as well only refer to http.

Maybe a hostname field would be the easiest, you can then also have another hostname then the server name.

**Comment by offiria** [comment]
Noted.. queuing for update

**Comment by offiria** [comment]
In configuration.php file, look for this line

public $force_ssl = '0';

and chaneg to

public $force_ssl = '2';

that should fix all the links. I've tested locally and it fixed all ssl link issues.
