### ISSUE TITLE
Pagination - Prev and Next Links may duplicate when in sub-directory.

### ISSUE THREAD

**Issue by JMSolo** [offiria/offiria#13]
<h2>Problem</h2>

Offiria when installed within a sub-directory, ie; http://offiria.yourdomain.com/youroffice/ will render duplicated domain errors within Pagination.  Links with the error will render as:<br />
<em>http://offiria.yourdomain.com/youroffice/youroffice/?start=10</em><br />
Links should (when correctly rendered) read as:<br />
<em>http://offiria.yourdomain.com/youroffice/?start=10</em><br /><br />

<h2>Solution</h2>

Open --> <em>youroffiriaroot-path</em> /templates/offiria/html/pagination.php<br />

<h5>Navigate to line #113 .. it will read as follows:</h5>

<div class="highlight"><pre>function pagination_item_active(&$item) {

```
return "<li class=\"active\"><a href=\"".rtrim(JURI::root(), '/').$item->link."\" title=\"".$item->text."\">".$item->text."</a></li>";
```

}</pre></div><br />

<h5>Change to:</h5>

<div class="highlight"><pre>function pagination_item_active(&$item) {

```
return "<li class=\"active\"><a href=\"".$item->link."\" title=\"".$item->text."\">".$item->text."</a></li>";
```

}</pre></div><br />
Now links within Pagination flow should render correctly without error.<br />
<b>PLEASE NOTE:</b> This is a fix that has worked for our offices. Our system specs are as follows:<br /><br />
PHP Version ---- 5.3.27<br />
Web Server ---- Apache/2.2.22<br />
Joomla! 2.5.14 Stable<br />
Other setups may or may not produce successful results.. so if you have this issue, please make a backup of your file first before committing to changes.

**Comment by offiria** [comment]
We are actually aware of a couple of issues when it comes to using offiria on a subfolder. Do post your findings here so we can queue it up for fixing.

**Comment by JMSolo** [comment]
Applied this fix to a root install and no issues resulted.  I'll create a pull request for further consideration.

**Comment by offiria** [comment]
Tested and pull accepted.. thanks!
