### ISSUE TITLE
Failed to install admin user

### ISSUE THREAD

**Issue by faizalheesyam** [offiria/offiria#130]
i tried to install Offiria in my local machine, started with providing database information, then account setup for offiria admin, Install, and failed in the next page.

![Failed to install admin user](https://f.cloud.github.com/assets/355451/2483364/d1e0bbec-b0ff-11e3-94c3-a4db2cc7cdba.png)

**Comment by stevekfrey** [comment]
I am also having this problem when installing the database. Did you find a solution to it?

**Comment by offiria** [comment]
There is a bug in the install script where it fails to install anonymous user in some server. I will upload a new build.

**Comment by faizalheesyam** [comment]
Cool.. Looking forward to it!

**Comment by stevekfrey** [comment]
Great, thanks! Please let me know when you have so I can try it again.

**Comment by offiria** [comment]
A new build has been uploaded. Version 2.1.1
