### ISSUE TITLE
Wrong username/password combination for Database Configuration

### ISSUE THREAD

**Issue by growthecommunity** [offiria/offiria#15]
While trying to install Offiria on my server I got this error, "Wrong username/password combination for Database Configuration"

I fixed this by changing line 17 in installer/models/database.php 
from "mysql:dbname=$dbname;host:=$host"
to "mysql:dbname=$dbname;host=$host"

After that I got to a screen that said "This is a fresh install of Offiria, database01 database will be removed (this action is not reversible) Confirm"
But confirming this caused the installer to crash.

I fixed this by changing line 97 in installer/index.php
from "DBConnection::connect($db_name, NULL,"
to "DBConnection::connect($db_name, $db_host,"

I believe this crash happened because I was not connecting to localhost.

Sorry about not committing this bug fix, I'm new to GitHub and just don't have time to figure it out right now. If I continue to work with Offiria I'll do it the right way next time.

**Comment by offiria** [comment]
Thank you. Look like a real issue. I will double check this and update it.

**Comment by offiria** [comment]
Fixed and merged
