### ISSUE TITLE
Deprecated functions

### ISSUE THREAD

**Issue by gahula** [offiria/offiria#155]
Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\wamp\www\offiria\libraries\joomla\filter\input.php on line 652

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\wamp\www\offiria\libraries\joomla\filter\input.php on line 654

**Comment by antony-yieldify** [comment]
I am also having this issue after having installed offiria 2.5

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\wamp\www\libraries\joomla\filter\input.php on line 652
Call Stack

# Time    Memory  Function    Location

1   0.0000  256448  {main}( )   ..\index.php:0

**Comment by gahula** [comment]
Seems this module is no longer supported.
