### ISSUE TITLE
Group Invites : Error : Invite Expire or non-valid

### ISSUE THREAD

**Issue by JMSolo** [offiria/offiria#2]
Group Invitations.

Invites to the main-stream work flawlessly.. Group Invites Fail saying credentials are revoked or expired.

UPDATE::
Sorted out the group invite functionality by adding in a column to the table _users_invite known as group_limited. 
Only problem is this still doesn't limit them to only that particular group.. they can still access the main feed.

Found  a diagram for this solution elsewhere - can't recall where though.
![dbchanges](https://f.cloud.github.com/assets/5215074/961654/254cd4f2-04dd-11e3-804e-96c27c3af5ec.PNG)

**Comment by offiria** [comment]
Noted... queue for 2.1.0 update

**Comment by offiria** [comment]
Fixed, but please use text instead of varchar. We can't anticipate the length of the group id that we need to store
