### ISSUE TITLE
Resized thumbnail cannot be saved

### ISSUE THREAD

**Issue by offiria** [offiria/offiria#30]
![change_avatar](https://f.cloud.github.com/assets/4747111/1101668/f4b916d0-17d7-11e3-9a79-b65a5b21fedf.png)

Clicking "save thumbnail" does not save the new resized thumbnail. Internally, it produce a 500-error

**Comment by JMSolo** [comment]
This is strange as the saving of a thumbnail once resized produces a success.  Additionally, no errors are thrown.

I can submit my offiria files if you like as my fork of offiria is out-of-date.  Perhaps you could try to duplicate the error with the files I submit to you.

I will browse through the edit.php (which I assume this is where the issue would be) and see if I can compare for any errors.

Although, it seems there are a few inconsistencies from one install to the next (which is expected).  IE; Events with Location Maps work on your install, yet the resizing of avatars does not work ... vice versa..

**Comment by offiria** [comment]
Yeah, it is working, seems that my local files was missing the original image. Once new avatar uploaded, everything works fine. Will close this.
