### ISSUE TITLE
PASSWORDS_DO_NOT_MATCH Text

### ISSUE THREAD

**Issue by sauanimal** [offiria/offiria#37]
If user changes his profile and password don't match, the user gets an error message containing constant PASSWORDS_DO_NOT_MATCH. It seems that in somewhere the text in english or other languages are not entered.

**Comment by JMSolo** [comment]
Line 65 within /root/components/com_profile/controllers/edit.php

Change:
<pre code>$mainframe->redirect(JRoute::_('index.php?option=com_profile&view=edit'), JText::_('PASSWORDS_DO_NOT_MATCH'), 'error');</pre code>

To:
<pre code>$mainframe->redirect(JRoute::_('index.php?option=com_profile&view=edit'), JText::_('COM_REGISTER_ERRMSG_PASSWORD_MISMATCH'), 'error');</pre code>

We'll submit a Pull Request for further review.

Illustration of Success
![password-error-message-fix](https://f.cloud.github.com/assets/5215074/1103866/6f4296f8-18cb-11e3-82e1-db7bcaf96250.png)

**Comment by offiria** [comment]
Tested, fixed.
