### ISSUE TITLE
Chat Feature Request

### ISSUE THREAD

**Issue by sauanimal** [offiria/offiria#45]
Is there plans to introduce chat functionality among users in Offiria? Some random examples:
http://www.phpfreechat.net/
http://sourceforge.net/projects/phpchatroom/
http://sourceforge.net/projects/php-chat/
http://www.cometchat.com/
http://css-tricks.com/jquery-php-chat/

Is there plans to introduce video conferencing, meeting and/or screen sharing functionality among users in Offiria? Some random examples:
http://openmeetings.apache.org/demo.html
https://code.google.com/p/video-chat/
http://www.red5chat.com/

**Comment by offiria** [comment]
Sorry, but there is no plan for chat system anytime soon. I will close this request for now.
