### ISSUE TITLE
Anonymous commenting problems

### ISSUE THREAD

**Issue by sauanimal** [offiria/offiria#46]
When inserting comments to some posts anonymously, the logged in user avatar/name is shown and also comment is marked as "New".
![offiria2](https://f.cloud.github.com/assets/5396912/1105921/1a8d82a2-1935-11e3-975d-1db68dd2a657.png)
![offiria1](https://f.cloud.github.com/assets/5396912/1105923/1a968064-1935-11e3-8680-0b1e9df7c1fd.png)

When doing complete reload of a pages, then the post is shown anonymously, as it should. But then the marking "New" has dissappeared. I would guess, that in Offiria there whould be nice, if ie streams, that are new (let's say 1 day or smht) are marked as "New". But i don't see nowhere else these markings when creating new items.
![offiria3](https://f.cloud.github.com/assets/5396912/1105922/1a8c603e-1935-11e3-84c9-28b33a8477a8.png)

**Comment by sauanimal** [comment]
Also, when posting anonymously, i will receive e-mail from system. But when posting non-anonymously, i will not...i could not figure out the logic behind that...

**Comment by offiria** [comment]
Noted wrt profile picture. As for email notification, the notification is sent to everyone that "subscribed" to the stream item, and the system doesn't know that it was you who post it, hence the notification will also be sent to you.

**Comment by offiria** [comment]
OK, the real issue is, the system actually need a user with username "anon". You can create such user (disable it) and the anonymous commenting would work fine. I will add a code that fix the avatar properly.

**Comment by sauanimal** [comment]
confirm, this workaround works

**Comment by JMSolo** [comment]
Confirmed.  This resolves the issue on our end.
