### ISSUE TITLE
YouTube link as a status field don't show image

### ISSUE THREAD

**Issue by sauanimal** [offiria/offiria#50]
After adding youtube link to status field and clicking save, the video duration, title and description are extracted but no thumbnail are shown:
![offiria1](https://f.cloud.github.com/assets/5396912/1106949/b37f32c2-1952-11e3-9073-9eb753159601.png)

PS! I have diffbot disabled under advanced settings.

I also tried the same thing in demo.offiria.com, but there it went to some kind of loop and nothing happened (under account of james):
![offiria2](https://f.cloud.github.com/assets/5396912/1106950/b380b052-1952-11e3-85cb-f15fbdf70b95.png)

**Comment by offiria** [comment]
I can verify that this is an issue. Some code are referring to an external assets.offiria.com , which is the old code from cloud edition.

**Comment by offiria** [comment]
Fixed..

**Comment by sauanimal** [comment]
Does not work, same symptoms in my site and also demo.offiria.com

I managed to fix, when removing urlencode in line 287:

```
<img class="message-content-video-thumbnail interactive" src="'. $video->thumb .'" embed_id="'.$videoid.'"  embed_type="videos"/>

```

**Comment by offiria** [comment]
Yes, that's the actual code. I did another commit but did not push it.
