### ISSUE TITLE
Empty links are created into database

### ISSUE THREAD

**Issue by sauanimal** [offiria/offiria#55]
When creating youtube/vimeo or smth other links via status messages, the empty links rows are created into the off_stream_links database table.

In the UI, under users content page it shows that the user has entered links, but nothing is shown:
![offiria1](https://f.cloud.github.com/assets/5396912/1112996/42448244-19f0-11e3-9500-eb61ad03c3f8.png)

**Comment by sauanimal** [comment]
Also, when adding multiple links in one message, it seems that the system don't know to separate them...

**Comment by offiria** [comment]
For multiple link, the system will only pick the first link it found

**Comment by offiria** [comment]
I can replicate the initial issue. Queuing for a fix.
