### ISSUE TITLE
View larger map link does not open correct location

### ISSUE THREAD

**Issue by offiria** [offiria/offiria#56]
It simply open google map of the current user location.

**Comment by sauanimal** [comment]
That's the thing, it shoudl open, but it does not:
![untitled1](https://f.cloud.github.com/assets/5396912/1116110/789148d8-1a35-11e3-9286-92673e81c405.png)

![untitled](https://f.cloud.github.com/assets/5396912/1116105/6bbc93b0-1a35-11e3-8cde-75f2b4e5f9ed.png)
