### ISSUE TITLE
Integration w social media

### ISSUE THREAD

**Issue by sauanimal** [offiria/offiria#57]
Is there some kind of social media integration also planned and in pipeline (ie facebook, twitter, pinterest, google groups)!? I would imagine that this would add extra egde to the product and also fit to social intranet concept.

**Comment by offiria** [comment]
Not at the moment, no. 

By the way, in the future, it would be great if you can ask questions in FB instead of here. I want to reserve github issues as actual issue tracker instead of a forum. It will help code contributor to focus. Thanks.
