### ISSUE TITLE
Flaw (XSS iFrame) in edit profile

### ISSUE THREAD

**Issue by AmirolAhmad** [offiria/offiria#6]
In the form 'pangkat', user can insert iFrame code and this totally can break all the script in user profile.

Here is the code that I used:

<iframe src=http://www.mapsofworld.com/images/world-countries-flags/malaysia-flag.gif <

You can sanitize this code from being executed.

![screen shot 2013-08-15 at 11 12 28 am](https://f.cloud.github.com/assets/1130863/966813/e2e24602-0558-11e3-9a4a-f3a7f02a52ef.png)
![office_apasaja](https://f.cloud.github.com/assets/1130863/966817/efdf609c-0558-11e3-9737-3890772e43a5.png)

**Comment by offiria** [comment]
Fixed.. Thanks!
