### ISSUE TITLE
File edit field bug

### ISSUE THREAD

**Issue by sauanimal** [offiria/offiria#61]
Go http://demo.offiria.com/component/stream/files and click Edit File.

Activate text field and press enter. Empty pages with some serialized data will be shown.

**Comment by offiria** [comment]
Can anyone replicate this in their local machine ?

**Comment by sauanimal** [comment]
Yes, i can replicate this in my local machine also, and the issue is related to the (at least partly) file \components\com_stream\controllers\files.php

line 96 (there are some other echo statements that needs to be checked aswell), that would be shown as serialised data, instead of the proper files page...

```
echo htmlspecialchars(json_encode($result), ENT_NOQUOTES);
```
