### ISSUE TITLE
PHP Notice in search view

### ISSUE THREAD

**Issue by sauanimal** [offiria/offiria#65]
Either by searching with top right corner field or inside stream (Search Updates), before the search results are shown, there is also a notice:

Notice: Trying to get property of non-object in /var/sites/demo.offiria.com/plugins/search/content/content.php on line 234

**Comment by offiria** [comment]
Can't seems to replicate this locally

**Comment by JMSolo** [comment]
Agreed.  We cannot replicate this either.  Not a local issue. I can see the issue on the demo however.

**Comment by sauanimal** [comment]
Same here, i only this notice in demo server, not my local copy (maybe some code is outdated in demo?)

**Comment by offiria** [comment]
Demo server does not have the most updated code. I will close this for now.
