### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by AmirolAhmad** [offiria/offiria#7]
Please take note on the screenshot below:

![sql-injection](https://f.cloud.github.com/assets/1130863/966887/2039c1ca-055d-11e3-9267-4393fdef3cb3.png)

**Comment by offiria** [comment]
Can you please explain how is this a SQL injection ?

**Comment by AmirolAhmad** [comment]
Hi.. sorry for the misleading subject above. That is no SQLi but the error seems related between is_array and in_array.
