### ISSUE TITLE
User invited only to specific group should not be allowed to post to public stream

### ISSUE THREAD

**Issue by offiria** [offiria/offiria#72]

**Comment by JMSolo** [comment]
Agreed.  We too have experienced this issue.  The group specific user can see and post to the mainstream. Furthermore, the group specific user can see all other groups within the office.

**Comment by offiria** [comment]
From my end, 
- they cannot actually see public stream, but they can post to public stream. 
- they cannot see the list of other groups.

**Comment by JMSolo** [comment]
Thanks for the response.  I look closer into this issue on my end.  It may be an issue on my end.  The test account I invited I had also assigned 'admin' privs.
