### ISSUE TITLE
Flaw (XSS No Filter Evasion) while posting a status

### ISSUE THREAD

**Issue by arvind-naidu** [offiria/offiria#8]
In the main page, by executing and posting a status with XSS No Filter Evasion code, Offiria malfunctions.

Injected code can be found at: https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet

As of now, only method of recovering from the problem is by reinstalling Offiria. Strongly suggest in sanitizing this problem from being executed in the future. 

![screenshot from 2013-08-23 22 07 25](https://f.cloud.github.com/assets/5022143/1016594/cf67b250-0bfd-11e3-9368-a246e06bbecf.png)
![screenshot from 2013-08-23 22 07 30](https://f.cloud.github.com/assets/5022143/1016599/eed77e72-0bfd-11e3-953f-303d4dec6b92.png)

**Comment by offiria** [comment]
Noted

**Comment by offiria** [comment]
Tested on latest code and seems to be working just fine. Mostly likely related to php warning error instead of security issues as we took great care with xss. Tested at our demo site and it work just fine. I will close this now. Do reopen if you detect it in the demo site

**Comment by arvind-naidu** [comment]
WIll definitely inform if there is any bugs found in the demo site.

Till then,
Cheers.
