### ISSUE TITLE
Directory Browsing Enabled

### ISSUE THREAD

**Issue by arvind-naidu** [offiria/offiria#9]
## Problem

Directory listing is enabled under http://ipaddress:80/offiria/media/jquery/. Directory listing may reveal unwanted hidden scripts which includes files, backup source files which can be accessed to read sensitive information.
## Solution

Disable directory browsing.  If this is required, make sure the listed files does not induce risks.
## Reference for Solution

For IIS, turn off directory browsing.
For Apache, use the 'Options -Indexes' directive to disable indexes in directory or via .htaccess:
. http://httpd.apache.org/docs/mod/core.html#options
. http://alamo.satlug.org/pipermail/satlug/2002-February/000053.html
. or create a default index.html for each directory.

![screenshot from 2013-08-24 17 37 32](https://f.cloud.github.com/assets/5022143/1020447/d31c0542-0ca0-11e3-945f-3600eb72b590.png)

**Comment by offiria** [comment]
We've a few directory using joomla default method (adding index.html). There might be a few more folder. I will keep this issue open until 2.1.0 release. Feel free to update this issue if you find any more folders.

**Comment by sauanimal** [comment]
I reviewed the current structure and looked for folders, which does not contain index.html. Below are my findings, hope this helps a bit. When going through the structure, i got a really strong feeling that there are a lot of content, that are not actually used for offiria functionality.

As i don't know the offiria code quite not so well yet, this really confuses the potential community, customers and developers (if for instance they would want to create additional functionality etc). Also this makes the offiria package quite big. I would recommend to create a issue for 'garbage collection' - the goal would be to remove excess folders/code/files, that are not actually used.

Folders without index.html
\updater 
\updater\apps
\templates\offiria\bootstrap
\templates\offiria\css\lib
\templates\offiria\html - most of the subfolders
\plugins\system\mobile
\plugins\system\oauth
\media\highchart\js & subfolders
\media\jquery\css\flick
\media\jquery\js
\media\less
\media\prettify
\media\system\swf
\media\tipsy & subfolders
\media\tipsy2 & subfolders
\media\tours & subfolders
\media\uploader
\libraries\HighRoller
\libraries\joomla\analytics
\libraries\joomla\utilities\integration
\language subfolders
\installer & most of the subfolders
\files & subfolders
\components\com_analytics & subfolders
\components\com_messaging & subfolders
\components\com_oauth\tables
\components\com_oauth\libraries
\components\com_profile\assets
\components\com_profile\models\fields
\components\com_profile\models\forms
\components\com_scripts
\components\com_stream\assets subfolders
\components\com_stream\libraries subfolders

**Comment by offiria** [comment]
I've fixed this in .htaccess level as well
