### ISSUE TITLE
New registered user has shown as a member of some groups

### ISSUE THREAD

**Issue by sauanimal** [offiria/offiria#90]
When new user has registered to the system, then by default he has not joined/followed no groups. In the left part, other groups shows like that - all groups are listed in that category.

But when looking groups page (stream/groups), then the user is shown for some reason, that he is a member of couple of groups. This is wrong. 

PS! It seems, that the new user is shown as a joined member of croups, that still does not have yet any members

**Comment by sauanimal** [comment]
Fix: groups.list.php

Line 113:

```
        $members = array();
        if ($group->get('members')) {
            $members = explode(',',$group->get('members'));
        }
```

And line 167:

```
            <?php if (count($members)) { ?>
            <label class="bold"><?php echo JText::_('COM_STREAM_LABEL_GROUP_MEMBERS'); ?>:</label>
            <?php
            foreach($members as $row){
                $user = JXFactory::getUser($row);
            ?>
            <span class="user-list">
                <a href="<?php echo $user->getURL(); ?>">
                <img title="<?php echo $this->escape($user->name); ?>" src="<?php echo $user->getThumbAvatarURL(); ?>" class="tips">
                </a>
            </span>
            <?php }
            } else { ?>
                <label class="bold"><?php echo JText::_('COM_STREAM_LABEL_NO_JOINED_MEMBER'); ?></label>
            <?php } ?>
```

**Comment by offiria** [comment]
Noted... will review and add this for 2.1.0

**Comment by offiria** [comment]
Fixed at data level, but the error message displayed is inaccurate. To be fixed under a different issue.
